name: travel_inspiration
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+7

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.1.4
  flutter_screenutil: ^5.5.2
#  google_sign_in: ^5.0.4
  video_player: ^2.1.6
  image_picker: ^0.8.1+3
  camera: ^0.9.4+2
  path_provider: ^2.0.8
  image_cropper: ^1.4.1
  country_code_picker: ^2.0.2
  #  pie_chart: ^5.0.0
  flutter_rating_bar: ^4.0.0
  google_maps_flutter: ^2.0.6
  flutter_polyline_points: ^1.0.0
  geolocator: ^7.6.2
  geocode: 1.0.1
#  geocoder: ^0.2.1
  in_app_purchase: ^1.0.9
  url_launcher: ^6.0.16

  intl: ^0.17.0
  shared_preferences: ^2.0.7
  http: ^0.13.3
  fluttertoast: ^8.0.8
  syncfusion_flutter_charts: ^19.2.62
  syncfusion_flutter_datepicker: ^19.2.55
  flutter_html: ^2.1.5
  flutter_slidable: ^1.1.0

  permission_handler: ^8.3.0
  android_intent: ^2.0.2
  firebase_messaging: ^10.0.9
#  firebase_messaging: ^7.0.3
#  firebase_auth: ^1.4.1
  local_auth: ^1.1.8
  firebase_auth: ^3.1.4
  firebase_core: ^1.8.0
  google_place: ^0.4.3
  syncfusion_flutter_sliders: ^19.4.40



  flutter_localizations:
    sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/videos/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Cagliostro
      fonts:
        - asset: assets/fonts/cagliostro/Cagliostro-Regular.ttf
          weight: 700
    #           style: italic
    - family: Courier Prime
      fonts:
        - asset: assets/fonts/courier_prime/Courier Prime.ttf
          weight: 700
    - family: Courier_Prime_Bold
      fonts:
        - asset: assets/fonts/courier_prime/Courier Prime Bold.ttf
          weight: 700

    - family: Courier_Prime_Bold_Italic
      fonts:
        - asset: assets/fonts/courier_prime/Courier Prime Bold Italic.ttf
          weight: 700
    - family: Courier_Prime_Italic
      fonts:
        - asset: assets/fonts/courier_prime/Courier Prime Italic.ttf
          weight: 700
    - family: Bodoni_Bold
      fonts:
        - asset: assets/fonts/bodoni.ttf
          weight: 700
    - family: Bodoni_Book
      fonts:
        - asset: assets/fonts/bodoni_book.ttf
          weight: 700

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
