import 'package:get/get.dart';

class TILanguages extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        'fr_FR': {
          "emailreq": "L'adresse e-mail est requise !", //French Language
          "emailvalid": "Veuillez entrer une adresse e-mail valide",
          "passwordreqOld": "Les anciens mots de passe sont requis",
          "passwordreqNew": "Un nouveau mot de passe est requis !",
          "passwordreq": "le mot de passe est requis !",
          "passwordreqvalid": "Le mot de passe ne répond pas aux exigences",
          "cgvvalid":
              "Veuillez vérifier les règles dans les conditions générales de ventes",
          "validName": "Veuillez saisir un nom valide",
          "dateofBirthreq": "La date de naissance est requise",
          "dateofVacationStart": "La date de vacances est requise !",
          "dateofVacationEnd": "La date de destination est requise ! ",
          "arrivalDate": "la date de départ est requise !",
          "toShare": "Partager :",
          "myHaudosContacts": "Mes contacts haudosséen.nes",
          "others": "Autres",
          "whatsApp": "WhatsApp",
          "email": "E-mail",
          "txtMsg": "Message Texte",
          "DETAILS": "DÉTAILS",
          "DIRECTION": "DIRECTION",
          "time": "TEMPS",
          "DISTANCE": "DISTANCE",
          "METHODE": "METHODE",
          "car": "Voiture",
          "ruleOne": "Ce trajet utilise un itinéraire avec péages.",
          "ruleTwo":
              "Une section de ce trajet nécessite le transport ferroviaire du véhicule.",
          "ruleThree": "Cet itinéraire traverse une frontière nationale.",
          "ruleFour":
              "Votre destination se trouve dans un autre fuseau horaire.",
          "validAddress": "Veuillez saisir une adresse valide",
          "validCodePostal": "Veuillez saisir un code postal valide",
          "validCity": "Veuillez saisir une ville valide :",
          "validPhoneNo": "Veuillez saisir un numéro de téléphone valide",
          "validAvtar": " Veuillez choisir votre photo de profil",
          "validProjName": "Veuillez saisir le nom du projet",
          "validPersonCount": "Veuillez ajouter une personne",
          "application_pour_des":
              "L’application pour des voyages inspirés & réfléchis",
          "laisse_tes_pas":
              "Laisse tes pas te guider vers ta destination idéale !",
          "je_suis_haudosseen": "Je suis Haudosséen.ne",
          "je_suis_haudosseen_multiline": "Je suis\n Haudosséen.ne",
          "devenir_haudosseen": "Devenir Haudosséen.ne",
          "devenir_haudosseen_multiLine": "Devenir\n Haudosséen.ne",
          "email": "EMAIL",
          "mot_de_passe": "MOT DE PASSE",
          "mot_de_passe_oublie": "Mot de passe oublié",
          "se_connecter": "Se connecter",
          "envoyer_email": "Envoyer l’email de récupération",
          "return_homepage": "Retourner à la page\nde connexion",
          "sent_mail_msg":
              "Un email a été envoyé à l’adresse email indiqué pour réinitialiser ton mot de passe. Retourne sur ta page de connexion lorsque ton mot de passe est modifié.",
          "spam_verify": "N’oublie pas de vérifier tes spams !",
          "accept_cgv": "Accepter les",
          "cgv": "CGV",
          "signin_with_google": "Se connecter\navec Google",
          "password_rules":
              "Le mot de passe doit avoir au minimum 8 caractères :\n- minuscules\n- 1 chiffre minimum\n- 1 caractère spécial\nminimum (@#!% « ;,?/:=+-_’&)",
          "cvg_rules":
              "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? »",
          "genial_tu_es": "Génial tu es parmi.e nous !",
          "actives_ton_compte": "Active ton compte depuis l'email reçu.",
          "commerce_aventure": "Commencer l’aventure",
          "create_profile": "CRÉÉ.E\n TON PROFIL",
          "add_nickname": "Ajouter un pseudo",
          "choose_option": "Choisissez l'option",
          "choose_date": "Choisissez une date",
          "camera": "Caméra",
          "gallery": "Galerie",
          "address": "Modifier mon adresse email",
          "postal_code": "Code postal",
          "city": "Ville",
          "phone_number": "Numéro de téléphone",
          "telephone_info":
              "Ton numéro de téléphone te servira seulement pour partager tes projets de vacances avec tes amis sur Haudos.",
          "uk": "Royaume - Uni",
          "country": "Pays",
          "date": "Date",
          "month": "Mois",
          "year": "Année",
          "date_of_birth": "Date de naissance",
          "select_date": "Sélectionne une date",
          "select_month": "Sélectionne un mois",
          "select_year": "Sélectionne une année",
          "settings": "PARAMÈTRES",
          "my_account": "MON COMPTE",
          "change_my_password": "Modifier mon mot de passe",
          "mode_of_transport_used": "Mode de transport utilisé",
          "language": "Langue",
          "become_premium": "Devenir premium",
          "notification": "Notifications",
          "privacy_policy": "Politique de confidentialité",
          "other_information": "AUTRES INFORMATIONS",
          "auters_info": "AUTRES\nINFORMATIONS",
          "terms_conditions": "Termes \& conditions",
          "faq": "FAQ",
          "sign_out": "Se déconnecter",
          "delete_my_account": "Supprimer mon compte",
          "txtTu": "Tu as une question ? \nTu trouveras ta réponse ici.",
          "txtSelectionneuntheme": "Sélectionne un thème",
          "current_password": "Mot de passe actuel",
          "new_password": "Nouveau mot de passe",
          "new_password_validated": "Nouveau mot de passe validé",
          "confirmation_msg":
              "Une confirmation a été envoyée à ton adresse email.",
          "back_to_settings": "Revenir aux paramètres",
          "back_to_menu": "Revenir au menu",
          "Repartiede": "Repartir de 0 kilomètre",
          "Comulermes": "Cumuler mes kilomètres",
          "txtComencer": "COMMENCER UNE NOUVELLE AVENTURE",
          "txtLeplus":
              "Le plus beau voyage c' est celui qu' on a pas encore fait.",
          "txtLoick": "Loïck Peyron\n Navigateur français",
          "txtRademaree": "Redémarre ton chemin de 0 kilomètre.",
          "txtReprendre": "Reprends ton chemin depuis tes kilomètres actuels.",
          "txtInspireModeCommencerle": "COMMENCER L'AVENTURE",
          "txtInspireMode": "MODE INSPIRÉ",
          "txtModeReflechi": "MODE RÉFLÉCHI",
          "txtChoisie": "CHOISI.E TON MODE DE PARCOURS",
          "txtTune":
              "Tu ne peux pas voyager sur un chemin sans etre toi meme le chemin.",
          "txtBouddha": "Bouddha",
          "txtLeModeReflechi":
              "Le mode réfléchi est destiné aux utilisateurs qui ont un projet de vacances planifié. Tu sais déjà quand tu souhaites voyager.",
          "txtLeModeInspire":
              "Le mode inspiré est destiné aux utilisateurs qui ont un projet de voyage et qui n’ont pas encore programmé de date.",
          "txtASTU": "AS-TU DÉJÀ UN NOM POUR TON PROJET ?",
          "txtLeVoyage":
              "Le voyage est une espèce de porte par où l’on sort de la réalité comme pour pénétrer dans une réalité inexplorée qui semble un rêve ",
          "txtGuyde": "Guy de Maupassant Écrivain français",
          "txtSitun":
              "Si tu n’as pas de nom de projet, celui-ci sera intitulé \« inspiré \» dans ton carnet de voyages.",
          "txtOUI": "OUI",
          "txtNON": "NON",
          "txtHaudospremium": "HAUDOS PREMIUM",
          "txtAbonmentMonth": "ABONNEMENT MENSUEL",
          "txtProchain": "Prochain prélèvement\n le 12 mars 2021",
          "txtAnnulable": "Annulable à tout moment sans frais.",
          "txtExclusive": "*Exclusivités",
          "txtFonctiona": "*Fonctionnalités à vie",
          "txtVoirles": "Voir les",
          "txtGaia": "GAIA",
          "txtVoyagede": "VOYAGER DE FAÇON ÉCOLO",
          "txtPourplus":
              "Pour plus d'informations et voir les consignes pour publier un article, tu peux aller voir la FAQ ou demander à Istya par email ou sur notre compte Facebook en postant sur sa rubrique du mardi.",
          "txtFAQ": "FAQ",
          "txtou": " ou demander a Istya par email ou sur notre compte ",
          "txtFacebook": "Facebook ",
          "txten": "en postant sur sa ",
          "txtrubri": "rubrique du mardi.",
          "txtEnvoie":
              "Envoie ton article à Gaia pour révision",
          "txtmodede": "Mode de transport utilisé",
          "txtchoisdetes": "Choisi.e tes modes de transports du quotidien",
          "txtmyCompte": "MON COMPTE",
          "txtLangue": "Langue",
          "txtlangFranlang": "Francais",
          "txtLangAnglais": "Anglais",
          "txtLangIspagnol": "Espagnol",
          "txtLangItalien": "Italien",
          "txtNotifications": "Notifications",
          "txtDestination": "Destinations de la semaine",
          "txtNotificationpush":
              "Notification push des 5 destinations en fonction de tes kilomètres",
          "txtKilometres": "Kilomètres à mi-parcours",
          "txtNotificationdu":
              "Notification du nombre de kilomètres parcourus à mi-parcours de la semaine",
          "txtVacanceen": "Vacances en approche",
          "txtRecevoir":
              "Recevoir une notification 5 jours avant la date de ton départ pour vérifier que tout est prêt",
          "txtDatelimite": "Date limite des destinations",
          "txtDatelimiteInfo":
              "Recevoir une notification lorsque la date limite de ton projet arrive à expiration",
          "txtFAQASKISTYA": "FAQ\n   ASK ISTYA",
          "txtCOMPTEPREMIUM": "COMPTE PREMIUM",
          "txtGENERAL": "GÉNÉRAL",
          "txtMONCARNET": "MON CARNET DE VOYAGE",
          "txtMESDOCUMENTS": "MES DOCUMENTS",
          "txtMONBUDGET": "MON BUDGET",
          "txtMAVALISE": "MA VALISE",
          "txtCARTEINTERACTIVE": "CARTE INTERACTIVE",
          "txtGAIAMOI": "GAIA & MOI",
          "txtMONHAUDOS": "MON HAUDOS",
          "txtCARNETDEVOYAGE": "CARNET DE VOYAGE",
          "txtMesdestinations": "Mes destinations haudos",
          "txtMesvilles": "Mes villes favorites",
          "txtMesprojets": "Mes projets de vacances",
          "txtMesprojets_multiline": "Mes projets\n de vacances",
          "txtPinDestination": "ÉPINGLER UNE DESTINATION",
          "txtfav": "Enregistré en favori",
          "txtHOTELS": "HÔTELS",
          "txtRESTAURANTS": "RESTAURANTS",
          "txtACTIVITES": "ACTIVITÉS",
          "txtVOLS": "VOLS",
          "txtTRAINS": "TRAINS",
          "txtROUTE": "ROUTE",
          "txtEPINGLERUNE": "ÉPINGLER UNE DESTINATION",
          "txtADVENTURE2023": "ADVENTURE2023",
          "GPOWERHOLIDAYS": "GPOWERHOLIDAYS",
          "txtBAEME": "BAE&ME",
          "txtSUNSET21CANNES": "SUNSET21 - CANNES",
          "txtMONTPELLIER": "MONTPELLIER",
          "txtRechercherunhotel": "Rechercher un hôtel",
          "txtHOTELSEPINGLES": "HÔTELS ÉPINGLÉS",
          "txtRechercherunrestaurant": "Rechercher un restaurant",
          "txtRechercherunactivity": "Rechercher une activité",
          "txtRESTAURANTSEPINGLES": "RESTAURANTS ÉPINGLÉS",
          "txtACTIVITYSEPINGLES": "ACTIVITÉ ÉPINGLÉS",
          "txtRechercherunvol": "Rechercher un vol",
          "txtMESVOLS": "MES VOLS",
          "txtALLER": "ALLER",
          "txtRETOUR": "RETOUR",
          "txtDepuis": "Depuis:",
          "txtOu": "Où?",
          "txtQuand": "Quand?",
          "txtPassagers": "Passagers",
          "txtRechercher": "Rechercher",
          "txtJevoyagedepuis": "Je voyage depuis",
          "txtJevoyageVers": "Je voyage vers",
          "pinned": "Épinglé!",
          "txtValider": "Valider",
          "txtChoixdesdates": "Choix des dates",
          "dob_update_msg": "Tes informations ont bien été enregistrées !",
          "name_of_project": "NOM DU PROJET",
          "my_vacation_date": "Ma date de vacances",
          "my_notification_date":"Ma date de notification",
          "deadline_deatination_date":
              "Date limite pour recevoir mes destinations",
          "number_of_person": "Nombre de personnes",
          "show_mode_msg":
              "Retrouve tes projets de vacances dans ton carnet de voyage et modifies ton mode de transport dans les paramètres.",
          "profile": "PROFIL",
          "gaia": "GAIA",
          "inspire_mode": "MODE INSPIRÉ",
          "journey_always_start":
              "Un voyage de 1000 kilomètres commence toujours par un pas",
          "lao_tseu": "Lao Tseu",
          "see_my_journey": "VOIR MON PARCOURS",
          "my_trvel_book": "MON CARNET DE VOYAGE",
          "project_name_info":
              "Retrouve tes projets de vacances dans ton carnet de voyage.",
          "reflect_mode": "MODE REFLÉCHI",
          "current_destination": "Destinations en cours",
          "premium_account": "COMPTE PREMIUM",
          "projects": "PROJETS",
          "total_km": "Kilomètres parcourus au total",
          "inspire": "Inspiré",
          "reflect": "Réfléchi",
          "premium": "PREMIUM",
          "my_documents": "MES DOCUMENTS",
          "my_budget": "MON BUDGET",
          "my_suitcase": "MA VALISE",
          "intractive_map": "CARTE INTERACTIVE",
          "my_haudos": "MON HAUDOS",
          "future": "À VENIR",
          "to_buy": "ACHETER",
          "see_sales_condition": "Voir les termes et conditions",
          "premium_desc":
              "L’arrêt d’un compte premium annule tous tes avantages et fonctionnalités.",
          "premium_info":
              "Le compte premium te donne accès à toutes les fonctionnalités, à des avantages exclusifs et des avant-premières Haudos.",
          "premium_annual": "Premium annuel",
          "premium_monthly": "Premium mensuel",
          "document_info":
              "Épingle, copie, photographie tes documents électroniques pour ne jamais les perdre de vue.",
          "document_desc":
              "L’achat des fonctionnalités individuelles sont à vie",
          "items_offered": "*3 articles offerts",
          "budget_info":
              "Contrôle et détermine ton budget de vacances en fonction de ton projet et de tes envies.",
          "carte_info":
              "Interagis et croise le chemin d’autres haudosséen.nes qui dispose de la fonctionnalité et partage tes projets.",
          "mon_haudos_info":
              "Créé.e ton circuit de vacances et accède à toutes les informations pour être bien préparé.e pour tout planifier.",
          "valise_info":
              "Fais ton inventaire de tes affaires avant ton départ pour être sûr de ne rien oublier.",
          "full_version": "Version complète",
          "purchase_only": "Achat seul*",
          "each_item_added": "Chaque article ajouté",
          "premium_account_allows_you": "Le compte premium te permet :",
          "premium_account_allows_msg":
              "L’accès à toutes les fonctionnalités de l’application même après les mis à jours*\nAvantages exclusifs\nAccès en avant-premières des\nfonctionnalités Haudos.",
          "condition_msg":
              "*L’annulation du compte premium supprime tes avantages et les fonctionnalités payantes.",
          "see_terms_conditins_of_sale":
              "Voir termes et conditions générales de vente.",
          "delete_ac_msg":
              "La suppression de ton compte Haudos est irrévocable. Tu perdras toutes tes fonctionnalités acquises et avantages de ton compte premium (si compte premium). Tu n'auras plus accès à tes projets de vacances, ni aux partages fait avec les autres utilisateurs.\n\nSi tu souhaites revenir sur l'application, tu devras te recréer un compte et acheter les fonctionnalités individuellement ou souscrire à nouveau à un compte premium. Comme alternative tu peux te déconnecter et revenir quand tu veux.",
          "delete_warn_msg":
              "Tu peux toujours faire marche arrière et continuer ton chemin avec nous.",
          "changed_my_mind": "J’ai changé d’avis",
          "account_deletion": "Suppression du compte",
          "account_deletion_msg":
              "Nous espérons te revoir parmi nous ! Continue ton aventure Haudos via nos réseaux sociaux",
          "haudosapp": "@Haudosapp",
          "create_new_project": "CRÉER UN NOUVEAU PROJET",
          "vacation_date": "Date de vacances",
          "delete_destination": "SUPPRIMER UNE DESTINATION",
          "delete_destination_msg":
              "Es-tu sûr.e de vouloir supprimer cette destination de ton carnet de voyages ? \n Tu ne pourras plus la revoir même si tu repars de zéro kilomètre.",
          "remove": "Supprimer \?",
          "description": "Description",
          "commodites": "Commodités",
          "room_types": "Types de chambres",
          "hours": "Horaires",
          "picture_gallery": "Galerie photos",
          "review": "Avis",
          "read_all_reviews": "Voir tous les avis",
          "to_book": "Réserver",
          "the_legal": "LE REGAL",
          "find_road_route": "Rechercher un itinéraire de route",
          "my_routes": "MES ROUTES",
          "txtArretermonparcours": "Arrêter mon parcours",
          "stop_journey": "Carnet de voyage",
          "choose_destination_complete_vacation_plan":
              "Choisi.e une destination pour compléter ton projet de vacances.",
          "txtAdults": "Adultes",
          "txtAdultSubTitle": "Au-dessus de 12 ans",
          "txtChildren": "Enfants",
          "txtChildrenSubTitle": "2 à 12 ans",
          "txtBabe": "Bébé",
          "txtBabeSubTitle": "En dessous de 2 ans",
          "txtFlightPopupData":
              "Pour éviter d’écrire manuellement ton vol, achètes la fonctionnalité « mes documents » dans la galerie.",
          "txtDeviensPremium": "Deviens Premium",
          "txtRechercheruntrain": "Rechercher un train",
          "add_flight_manually": "Ajouter un vol manuellement",
          "txtMesTrains": "MES TRAINS",
          "txtTotal": "TOTAL",
          "txtReserversurle": "Réserver sur le site partenaire",
          "find_train": "Rechercher un train",
          "my_trains": "MES TRAINS",
          "txtNoInternetConnection": "Pas de connexion Internet",
          "txtNoRecordFound": "Aucun résultat trouvé !",
          "project_release_in_reflect": "Projet réalisé en mode réfléchi",
          "project_release_in_inspire": "Projet réalisé en mode inspiré",
          "travel": "Je voyage :",
          "Departure": "Départ",
          "Arrival": "Arrivée",
          "Arrival_date": "Date d’arrivée",
          "Date": "Date",
          "Month": "Mois",
          "Year": "Année",
          "Date_of_departure": "Date de départ",
          "Airline_company": "Compagnie aérienne",
          "TICKET": "RÉFÉRENCE TICKET",
          "logout": "Log Out",
          "logoutMsg":
              "Êtes-vous sûr.e de vouloir vous déconnecter de l’application ?",
          "Yes": "Oui",
          "No": "Non",
          "addRoute": "Ajouter\n l’itinéraire",
          "read_more": "Lire la suite...",
          "Filtrer": "Filtrer",
          "avec_escale": "avec escale",
          "Prix": "Prix",
          "sans_escale": "sans escale",
          "Trier_par": "Trier par",
          "Prix_croissant": "Prix croissant",
          "Prix_décroissant": "Prix décroissant",
          "Courte_durée": "Courte durée",
          "Longue_durée": "Longue durée",
          "Appliquer": "Appliquer",
          "location_required": "L'emplacement est requis!",
          "date_required": "La date est requise !",
          "flight_required": "Veuillez sélectionner le type de vol !",
          "travel_class_required":
              "Veuillez sélectionner la classe de voyage !",
          "comming_soon": "À venir...",
          "create_later": "CRÉER PLUS TARD",
          "change_my_number": "Modifier mon numéro",
          "notify_title":
              "Hey Haudos2021, regardes où tes pas t’ont mené jusqu’à présent.",
          "notify_subtitle":
              "Retrouves tes destinations dans ton carnet de voyage pour explorer les hôtels, restaurants et activités. Découvres également les disponibilités aériennes et ferroviaires.",
          "change_phone_no": "Modifier mon numéro de téléphone:",
          "new_number": "Nouveau numéro",
          "go_on_way": "Continuer mon chemin",
          "you_hv_done": "Tu as fais",
          "km": "kilomètres !",
          "choose_dest_title":
              "Choisi.e une destination pour créer un projet de vacances.",
          "choose_to": "Je choisi.e de:",
          "or":"ou",
        },
        'en_US': {
          "emailreq": "The e-mail address is required!", //English Language
          "emailvalid": "Please enter a valid email address",
          "passwordreqOld": "The old passwords are required",
          "passwordreqNew": "A new password is required!",
          "passwordreq": "Password is required!",
          "passwordreqvalid": "The password does not meet the requirements.",
          "cgvvalid":
              "Please check the terms and conditions if you wish to continue",
          "validName": "Please enter a valid name",
          "dateofBirthreq": "The date of birth is required",
          "dateofVacationStart": "The holiday date is required!",
          "dateofVacationEnd": "The date of destination is required!",
          "arrivalDate": "The departure date is required !",
          "toShare": "To share :",
          "add_flight_manually": "Add a flight manually",
          "myHaudosContacts": "My Haudos contacts",
          "others": "Others",
          "whatsApp": "WhatsApp",
          "email": "E-mail",
          "txtMsg": "Text Message",
          "DETAILS": "DETAILS",
          "DIRECTION": "DIRECTION",
          "time": "TIME",
          "DISTANCE": "DISTANCE",
          "METHODE": "METHODE",
          "car": "Car",
          "ruleOne": "This route uses a toll route.",
          "ruleTwo":
              "One section of this route requires the vehicle to be transported by rail.",
          "ruleThree": "This route crosses a national border.",
          "ruleFour": "Your destination is in a different time zone.",
          "validAddress": "Please enter a valid address",
          "validCodePostal": "Please enter a valid postal code",
          "validCity": "Please enter a valid city:",
          "validPhoneNo": "Please enter a valid phone number",
          "validAvtar": "Please choose your profile photo",
          "validProjName": "Please enter the name of the project",
          "validPersonCount": "Please add a person",
          "application_pour_des":
              "The application for inspired & reflective trips",
          "laisse_tes_pas":
              "Let your miles guide you to your ideal destination!",
          "je_suis_haudosseen": "I am Haudossean",
          "je_suis_haudosseen_multiline": "I am Haudossean",
          "devenir_haudosseen": "Become Haudossean",
          "devenir_haudosseen_multiLine": "Become Haudossean",
          "email": "EMAIL",
          "mot_de_passe": "PASSWORD",
          "mot_de_passe_oublie": "Forgot your password",
          "se_connecter": "Log in",
          "envoyer_email": "Send recovery email",
          "return_homepage": "Return to the connection page",
          "sent_mail_msg":
              "An email has been sent to the email address indicated to reset your password. Returns on your login page when your password is changed.",
          "spam_verify": "Do not forget to check your spam!",
          "accept_cgv": "Accept the",
          "cgv": " T&Cs",
          "signin_with_google": "Connect \n avec Google",
          "password_rules":
              "The password must have at least 8 characters: \n- lowercase \n- 1 minimum number \n- 1 special character \nminimum (@ #!% ;,? /: = + -_ '&)",
          "cvg_rules":
              "SED UT Persicis Ande Omnis Iste Natus Error Sit Volupatem accuses Doloremque Laudantium, Totam Rem Aperiam, Eaque Ipsa Quae AB ​​Illo Inventore Veritatis and Quasi Architecto Beatae Vitae Dicta Sunt Explicabo. Nemo Enim Ipsam Volupateem Quia Voluptas Sit Aspernatur Aut Odit Auto Fugit, SED Quia Consequuntur Magni Dolores EOS who ratione Volupateem Sequi Nescunt. NEQUE PORRO QUISQUAM EST, WHO DOLOREM IPSUM QUA DOLOR SIT AMET, CONSECTUR, ADIPISCI VELIT, SED QUA NOM NUMQUAM EIUS MODE TEMPORA INCUPUNT UT LABORE AND DOLORE MAGNAM ALIQUAM QUARAT VOLUPTATEM. Ut Enim Ad Mini Veniam, Quis Nostrum Exercitationem Ullam Corpory acknowledged Laboriosam, Nisi Ut Aliquid Ex Ea Commodi Consequatur? QUIS AUTY VEL EUM IURE REPREHENDERIT WHO IN EA VOLUPTATE VELIT ESSE QUAM NIHIL MOLLETIAE CONSEQUATUR, VEL ILLUM WHO DOLOREM EUM FUGIAT QUT VOLUPTAS Nulla Pariatur? »",
          "genial_tu_es": "Great you are with us !",
          "actives_ton_compte": "Active your account from the email received.",
          "commerce_aventure": "Start the adventure",
          "create_profile": "Create \n your profile",
          "add_nickname": "Add a userName",
          "choose_option": "Choose the option",
          "choose_date": "Choose a date",
          "camera": "Camera",
          "gallery": "Gallery",
          "address": "Change My Address Email",
          "postal_code": "Postal code",
          "city": "City",
          "phone_number": "Phone number",
          "telephone_info":
              "Your phone number will only serve you to share your holiday project with your friends on Haudos.",
          "uk": "United Kingdom",
          "country": "Country",
          "date": "Dated",
          "month": "Month",
          "year": "Year",
          "date_of_birth": "Date of Birth",
          "select_date": "Selects a date",
          "select_month": "Select a month",
          "select_year": "Select a year",
          "settings": "SETTINGS",
          "my_account": "MY ACCOUNT",
          "change_my_password": "Change my password",
          "mode_of_transport_used": "Mode of transport used",
          "language": "language",
          "become_premium": "Premium",
          "notification": "Notifications",
          "privacy_policy": "Privacy Policy",
          "other_information": "OTHER INFORMATION",
          "auters_info": "Other \n informations",
          "terms_conditions": "Terms \& Conditions",
          "faq": "Faq",
          "sign_out": "Sign out",
          "delete_my_account": "Delete my account",
          "txtTu": "You have a question ? \nYou will find your answer here.",
          "txtSelectionneuntheme": "Select a theme",
          "current_password": "Current Password",
          "new_password": "New Password",
          "new_password_validated": "New password validated",
          "confirmation_msg":
              "A confirmation has been sent on your email address.",
          "back_to_settings": "Return to settings",
          "back_to_menu": "Return to the menu",
          "Repartiede": "Restart from 0 kilometers",
          "Comulermes": "Cumulate my kilometers",
          "txtComencer": "Start a new adventure",
          "txtLeplus":
              "The most beautiful journey is the one that hasn't been done yet.",
          "txtLoick": "Loick Peyron\n French Explorer",
          "txtRademaree": "Restart your journey from 0 kilometers.",
          "txtReprendre": "Resume your path from your current kilometers.",
          "txtInspireModeCommencerle": "Start the adventure",
          "txtInspireMode": "Inspired mode",
          "txtModeReflechi": "Reflective mode",
          "txtChoisie": "Choose your travel mode",
          "txtTune":
              "You cannot travel the path until you have become the path itself",
          "txtBouddha": "Buddha",
          "txtLeModeReflechi":
              "Reflective mode is for users who have a planned vacation. You already know when you want to travel.",
          "txtLeModeInspire":
              "The inspired mode is for users who have a travel plan but have not yet scheduled a date.",
          "txtASTU": "Do you have a name for your project?",
          "txtLeVoyage":
              "Travel is some kind of gate by which one leaves reality, just as to enter an unexplored reality that seems a dream.",
          "txtGuyde": "Guy de Maupassant French writer",
          "txtSitun":
              "If you don't have a project name, it will be entitled \"inspired\" in you travel book.",
          "txtOUI": "YES",
          "txtNON": "NO",
          "txtHaudospremium": "Haudos Premium",
          "txtAbonmentMonth": "MONTHLY SUBSCRIPTION",
          "txtProchain": "Next payment on",
          "txtAnnulable": "Cancellation at any time without fees.",
          "txtExclusive": "* Exclusivities",
          "txtFonctiona": "* Features for life",
          "txtVoirles": "See the",
          "txtGaia": "Gaia",
          "txtVoyagede": "eco-travel",
          "txtPourplus":
              "For more information and see the consignps to publish an article, you can go see the",
          "txtFAQ": "Faq",
          "txtou": "or ask Istya by email or on our account",
          "txtFacebook": "Facebook",
          "txten": "by posting his",
          "txtrubri": "Tuesday's heading.",
          "txtEnvoie": "Send your article a gaia for review",
          "txtmodede": "Mode of transport used",
          "txtchoisdetes": "Choose your daily modes of transport",
          "txtmyCompte": "MY ACCOUNT",
          "txtLangue": "Language",
          "txtlangFranlang": "French",
          "txtLangAnglais": "English",
          "txtLangIspagnol": "Espagnol",
          "txtLangItalien": "Italian",
          "txtNotifications": "Notifications",
          "txtDestination": "Destinations of the week",
          "txtNotificationpush":
              "Push notification of the 5 destinations according to your kilometers",
          "txtKilometres": "Kilometers to midway point",
          "txtNotificationdu":
              "Notifications of the number of kilometers traveled midway from the week",
          "txtVacanceen": "Approaching holidays",
          "txtRecevoir":
              "Receive a notification 5 days before the date of your departure to verify that everything is ready",
          "txtDatelimite": "Deadline for destinations",
          "txtDatelimiteInfo":
              "Receive notification when the deadline for your project expires",
          "txtFAQASKISTYA": "FAQ\n   ASK ISTYA",
          "txtCOMPTEPREMIUM": "Premium account",
          "txtGENERAL": "GENERAL",
          "txtMONCARNET": "MY TRAVEL BOOK",
          "txtMESDOCUMENTS": "MY DOCUMENTS",
          "txtMONBUDGET": "MY BUDGET",
          "txtMAVALISE": "MY SUITCASE",
          "txtCARTEINTERACTIVE": "Interactive map",
          "txtGAIAMOI": "Gaia & Me",
          "txtMONHAUDOS": "My haudos",
          "txtCARNETDEVOYAGE": "Travel book",
          "txtMesdestinations": "My haudos destinations",
          "txtMesvilles": "My favorite cities",
          "txtMesprojets": "My holiday projects",
          "txtMesprojets_multiline": "My holiday projects",
          "txtPinDestination": "Pin",
          "txtfav": "Favorite",
          "txtHOTELS": "Hotels",
          "txtRESTAURANTS": "Restaurants",
          "txtACTIVITES": "ACTIVITIES",
          "txtVOLS": "Flights",
          "txtTRAINS": "Trains",
          "txtROUTE": "ROAD",
          "txtEPINGLERUNE": "Pin",
          "txtADVENTURE2023": "Adventure2023",
          "GPOWERHOLIDAYS": "Gpowerholidays",
          "txtBAEME": "BAE & ME",
          "txtSUNSET21CANNES": "Sunset21 - Cannes",
          "txtMONTPELLIER": "Montpellier",
          "txtRechercherunhotel": "Search for a hotel",
          "txtHOTELSEPINGLES": "Pinned hotels",
          "txtRechercherunrestaurant": "Search for a restaurant",
          "txtRechercherunactivity": "Search for an activity",
          "txtRESTAURANTSEPINGLES": "Pinned restaurants",
          "txtACTIVITYSEPINGLES": "Pinned activities",
          "txtRechercherunvol": "Search for a flight",
          "txtMESVOLS": "My flights",
          "txtALLER": "ONE WAY",
          "txtRETOUR": "RETURN",
          "txtDepuis": "From:",
          "txtOu": "To?",
          "txtQuand": "When?",
          "txtPassagers": "Passengers",
          "txtRechercher": "SEARCH",
          "txtJevoyagedepuis": "I travel from",
          "txtJevoyageVers": "I travel to",
          "pinned": "Pin!",
          "txtValider": "Confirm",
          "txtChoixdesdates": "Choice of dates",
          "dob_update_msg": "Your information has been recorded!",
          "name_of_project": "NAME OF THE PROJECT",
          "my_vacation_date": "My holiday date",
          "my_notification_date": "My notification date",
          "deadline_deatination_date": "Deadline to receive my destinations",
          "number_of_person": "Number of persons",
          "show_mode_msg":
              "Find your holiday plans in your travel diary and modify your mode of transport in the settings.",
          "profile": "PROFILE",

          "gaia": "Gaia",
          "inspire_mode": "Inspired mode",
          "journey_always_start":
              "The journey of a thousand miles begins with a single step",
          "lao_tseu": "Lao Tzu",
          "see_my_journey": "See my journey",
          "my_trvel_book": "MY TRAVEL BOOK",
          "project_name_info": "Find your holiday plans in your travel book.",
          "reflect_mode": "Reflective mode",
          "current_destination": "Destinations in progress",
          "premium_account": "Premium account",
          "projects": "PROJECTS",
          "total_km": "Total kilometers travelled",
          "inspire": "Inspired",
          "reflect": "Reflective",
          "premium": "Premium",
          "my_documents": "MY DOCUMENTS",
          "my_budget": "MY BUDGET",
          "my_suitcase": "My LUGGAGE",
          "intractive_map": "Interactive map",
          "my_haudos": "My haudos",
          "future": "Coming soon",
          "to_buy": "BUY",
          "see_sales_condition": "See terms and conditions",
          "premium_desc":
              "Ending a premium account cancels all your benefits and features.",
          "premium_info":
              "The Premium account gives you access to all features, exclusive benefits and Haudos updates.",
          "premium_annual": "Premium annual",
          "premium_monthly": "Premium monthly",
          "document_info":
              "Pin, copy, photograph your electronic documents to never lose sight of them.",
          "document_desc":
              "The purchase of individual features are valid for life",
          "budget_info":
              "Control and determine your vacation budget based on your project and your desires.",
          "carte_info":
              "Interact and cross paths with other haudosseans who has the functionality and shares your projects.",
          "mon_haudos_info":
              "Create your vacation circuit and access all information to be well prepared to plan everything.",
          "valise_info":
              "Make your inventory of your things before you leave to be sure you don't forget anything.",
          "full_version": "Full version",
          "purchase_only": "Single purchase *",
          "each_item_added": "Each item added",
          "items_offered": "*3 articles offered",
          "premium_account_allows_you": "The Premium account allows you:",
          "premium_account_allows_msg":
              "Access to all the features of \nFeatures for life * \nExclusive benefits \nEarly access to Haudos features \n Advantages in competitions",
          "condition_msg":
              "*Cancellation of the premium account removes your benefits and paid features.",
          "see_terms_conditins_of_sale": "See terms and conditions.",
          "delete_ac_msg":
              "The deletion of your Haudos account is irreversible. You will lose all your purchased features and benefits of your premium account (if premium account). You will no longer have access to your vacation plans, nor to the one shares made with other users. \n \n  If you want to come back to the application, you will have to create a new account and buy the features individually or subscribe to a premium account again. Alternatively, you can log out and come back whenever you want.",
          "delete_warn_msg":
              "You can always go back and continue your way with us.",
          "changed_my_mind": "I changed my mind",
          "account_deletion": "Deleting the account",
          "account_deletion_msg":
              "We hope to see you again! Continue your Haudos adventure via our social media",
          "haudosapp": "@Haudosapp",
          "create_new_project": "Create a new project",
          "vacation_date": "Holiday date",
          "delete_destination": "Delete a destination",
          "delete_destination_msg":
              "Are you sure you want to delete this destination from your travel log? \n You won't be able to see it again even if you start from zero kilometer.",
          "remove": "Delete ?",
          "description": "Description",
          "commodites": "Amenities",
          "room_types": "Types of rooms",
          "hours": "Hours",
          "picture_gallery": "Photo gallery",
          "review": "Reviews",
          "read_all_reviews": "Read all reviews",
          "to_book": "Make a reservation",
          "the_legal": "The regal",
          "find_road_route": "Search for a route itineray",
          "my_routes": "My routes",
          "txtArretermonparcours": "Stop my journey",
          "stop_journey": "Travel book",
          "choose_destination_complete_vacation_plan":
              "Choose a destination to complete your vacation plan.",
          "txtAdults": "Adults",
          "txtAdultSubTitle": "Over 12 years old",
          "txtChildren": "Children",
          "txtChildrenSubTitle": "2 to 12 years old",
          "txtBabe": "baby",
          "txtBabeSubTitle": "Under 2 years old",
          "txtFlightPopupData":
              "To avoid manually writing your flight, buy the functionality \"My documents\" in the gallery.",
          "txtDeviensPremium": "Become Premium",
          "txtRechercheruntrain": "Search for a train",
          "txtMesTrains": "My trains",
          "txtTotal": "TOTAL",
          "txtReserversurle": "Book on the third party website",
          "find_train": "Search for a train",
          "my_trains": "My trains",
          "txtNoInternetConnection": "No internet connection",
          "txtNoRecordFound": "NO RECORD FOUND!",
          "project_release_in_reflect": "Project made in reflective mode",
          "project_release_in_inspire": "Project made in inspired mode",
          "travel": "I travel :",
          "Departure": "Departure",
          "Arrival": "Arrival",
          "Arrival_date": "Arrival date",
          "Date": "Date",
          "Month": "Month",
          "Year": "Year",
          "Date_of_departure": "Date of departure",
          "Airline_company": "Airline company",
          "TICKET": "TICKET REFERENCE",
          "logout": "Log Out",
          "logoutMsg": "Are you sure you want to sign out from the app?",
          "Yes": "Yes",
          "No": "No",
          "addRoute": "Add route",
          "read_more": "Read more...",

          "Filtrer": "Filter",
          "avec_escale": "stopover",
          "Prix": "Price",
          "sans_escale": "nonstop",
          "Trier_par": "sort by",
          "Prix_croissant": "Ascending price",
          "Prix_décroissant": "Decreasing price",
          "Courte_durée": "Short duration",
          "Longue_durée": "Long duration",
          "Appliquer": "Apply",
          "location_required": "Location is required!",
          "date_required": "Date is required !",
          "flight_required": "Please Select Flight Type !",
          "travel_class_required": "Please Select Travel Class !",
          "comming_soon": "Comming Soon...",
          "create_later": "CREATE LATER",
          "change_my_number": "Modify my number",
          "notify_title":
              "Hey Haudos2021, look where your steps have taken you so far.",
          "notify_subtitle":
              "Find your destinations in your travel diary to explore hotels, restaurants and activities. Also discover air and rail availability.",
          "change_phone_no": "Change my phone number:",
          "new_number": "New number",
          "go_on_way": "Go on my way",
          "you_hv_done": "You have done",
          "km": "kilometers!",
          "choose_dest_title":
              "Choose a destination to create a vacation plan.",
          "choose_to": "I choose to:",
          "or":"OR",
        },
      };
}
